name: Build and Push to ECR

on:
  push:
    branches: [main]
      
permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: juju
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push Docker image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Load image variable
        run: echo "image=${{ env.image }}" >> $GITHUB_ENV
        
      - name: fetch manifest repository
        uses: actions/checkout@v4
        with:
          repository: EunOrganization/manifest-repository
          token: ${{ secrets.ACTION_TOKEN }}
          path: manifest
          fetch-depth: 1
          
      - name: verify 'yq' installation   
        run: |
          wget -q https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: verify manifest file path and contents
        run: |
          ls -l manifest/manifest
          cd manifest/manifest
          cat deploy-time.yaml

      - name: update manifest file image tag
        run: |
          cd manifest/manifest
          echo "Image URL is $image"
          yq e -i '.spec.template.spec.containers.[0].image = "${{ env.image }}"' deploy-time.yaml
          cat deploy-time.yaml

      - name: verify Git setup
        run: |
          git --version
          
      - name: setup Repository
        working-directory: manifest/manifest
        run: |
          pwd
          git fetch origin main
          git config --global user.name "BaeEunaee"
          git config --global user.email "dmsdoqo0406@gmail.com"
          git config --global --get user.name
          git config --global --get user.email
          git remote set-url --push origin https://github.com/EunOrganization/manifest-repository.git

      - name: commit
        working-directory: manifest/manifest
        run: |
          pwd
          git add .
          git commit -m "Update image tags for ${{ github.sha }}"
          git push origin main
