name: Build and Push to ECR

on:
  push:
    branches: [main]
      
permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: juju
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: fetch manifest repository
        uses: actions/checkout@v4

      - name: Check files in manifest directory
        run: |
          echo "Listing files in the manifest directory:"
          cd manifest
          ls -al manifest
          pwd
          
      - name: update manifest file image tag      
        run: |
          wget -q https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          cd manifest/manifest
          yq e -i '.spec.template.spec.containers[0].image = "${{ steps.build-image.outputs.image }}"' 'deploy-time.yaml'

      - name: push to config repo
        uses: pina/github-action-push-to-another-repository@v1.7.2
        env:
          token: ${{ secrets.ACTION_TOKEN }}
        with:
          source-directory: "manifest/manifest"
          destination-github-username: "EunOrganization"
          destination-repository-name: "manifest-repository"
          user-email: dmsdoqo0406@gmail.com
          target-branch: main
          commit-message: "Change Image version to ${{ steps.build-image.outputs.image }}"
